name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      location:
        required: true
        type: string
      project:
        required: true
        type: string
    secrets:
      AZURE_SPN:
        required: true
jobs:
      
  deploy:

    name: 'Bicep Deployment'
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_SPN }}
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.9
        with:
            scope: subscription
            region: ${{ inputs.location }}
            template: ./src/bicep/main.bicep
            parameters: >
                environment=${{ inputs.environment }}
                location=${{ inputs.location }}
                project=${{ inputs.project }}