name: iac-dv-release-2
concurrency: dv-project

on: 
  push:
    branches: 
      - main
      - feature/dvproject-3
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
      - name: Lint
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
            az bicep build --file ./main.bicep
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: drop 
          path: '${{github.workspace}}/*'

  # Deploy to the dev environment.
  deploy-de:
    uses: ./.github/workflows/dv-deploy.yml
    needs: build
    with:
      environment: de
      location: centralindia
      project: dv
    secrets:
      AZURE_SPN: ${{ secrets.AZURE_SPN_CREDENTIAL }}

  deploy-te:
    uses: ./.github/workflows/dv-deploy.yml
    needs: deploy-de
    with:
      environment: te
      location: centralindia
      project: dv
    secrets:
      AZURE_SPN: ${{ secrets.AZURE_SPN_CREDENTIAL }}