name: iac-dv-release
concurrency: dv-project

on: 
  push:
    branches: 
      - main
      - feature/dvproject-2
  workflow_dispatch:

jobs:
  # Deploy to the dev environment.
  deploy-de:
    uses: ./.github/workflows/dv-deploy.yml
    with:
      environmentType: de
      location: centralindia
      project: dv
    secrets:
      AZURE_SPN: ${{ secrets.AZURE_SPN_CREDENTIAL }}

  deploy-te:
    uses: ./.github/workflows/dv-deploy.yml
    needs: deploy-de
    with:
      environmentType: te
      location: centralindia
      project: dv
    secrets:
      AZURE_SPN: ${{ secrets.AZURE_SPN_CREDENTIAL }}