# This is a Data Viewer Project

name: DV Project

on: 
  push:
    branches:
      - main
      - feature/dvproject
  workflow_dispatch:


jobs:
  lint: 
    uses: ./.github/workflows/lint.yml

    # Deploy to the test environment.
  ddeploy-test:
    uses: ./.github/workflows/dv-deploy.yml
    needs: lint
    with:
      environmentType: de
      resourceGroupName: rg-dv-de-cac
    secrets:
      AZURE_SPN: ${{ secrets.AZURE_SPN_CREDENTIAL }}
    