# Add 'root' label to any root file changes
root:
  - "*"

# Add 'AnyChange' label to any changes within the entire repository
AnyChange:
  - "**/*"

# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
Documentation:
  - "docs/**/*"
  - "docs/*"
