# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      env:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Environment Name'
        # Default value if no value is explicitly provided
        default: 'de'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.env }}"
  
  build:
    #The type of runner that the job will run on
    runs-on: windows-latest
    name: 'Build'
    steps:

      - uses: actions/checkout@v2 
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
          # ClientId of the Azure Service principal created.
      - name: Lint
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
            az bicep build --file ./main.bicep
      - name: Validate
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
          az group create --what-if --name rg-${{inputs.env}}-demo --location centralindia
          az deployment group create --what-if --resource-group   rg-${{inputs.env}}-demo --template-file ./main.bicep
